### ISSUE TITLE
[Features] Add possibility to change volume and stop audio

### ISSUE THREAD

**Issue by vdeville** [sbrl/soundbox#2]
Hello,
Can you add possibility to add volume parameter and stop method ?

Thanks

**Comment by sbrl** [comment]
Hey! Great suggestions, @MyTheValentinus. I've [released version 0.3](https://github.com/sbrl/soundbox/releases/tag/v0.3) that adds a volume control.

My first thought for allowing sounds to be stopped was to return the sound instance so that you can call `.pause()` on the `HTMLAudioElement`, but this doesn't work because when in `Promise` mode it has to return a promise. Also, that approach doesn't feel particularly 'clean' to me.

We could add a global `.stop(sound_name)` method, but this might stop another concurrent instance of a sound that we don't want to stop.

What do you suggest?

**Comment by vdeville** [comment]
Hello,
In my usage i need to only stop all sound, it's ok for me. But in global usage of this library i think it's better to work on real solution to stop specific sound.
Thanks

**Comment by vdeville** [comment]
Humm, juste little suggestion for the song volume, can you add possibility to change volume globally, and too for all currently playing song ? Not only on start method like 0.3 release ?

**Comment by sbrl** [comment]
Hey! I'm looking into it, and I can certainly add a `stop_all()` method. I can also add a default volume option too. Looking into it now.

**Comment by sbrl** [comment]
I've encountered a bug in GitHub pages, in which `*.jsm` files are returned with the incorrect mime type (`application/octet-stream` instead of `application/javascript`). To that end, the demo is broken until GitHub get back to me, but you can still run it locally.

**Comment by vdeville** [comment]
You can specify type on line where the file is import no ?

**Comment by sbrl** [comment]
Erm you can in a `<script>`, but I include Soundbox (the ES6 version) in an `import` statement in `example.js`. Since the es6 version has a file extension of `.jsm`, I've hit this issue.

Anyway, I've added `stop_all()` and `default_volume`. You can see how to use them in the README.

I'll just release v0.3.2 with these changes.

**Comment by sbrl** [comment]
Done! [Here it is](https://github.com/sbrl/soundbox/releases/tag/v0.3.2).

Does that add both of your requested features, @MyTheValentinus? I'll reopen this issue if it doesn't.

**Comment by vdeville** [comment]
Yeah thanks ;)

**Comment by vdeville** [comment]
Is not better to send default_volume parameter in constructor when you create the Soundbox() object ?

**Comment by sbrl** [comment]
Erm I could add a constructor parameter, but I'd like to hold off on that as it seems somewhat arbitrary, and I'm not sure what other settings we'll want to add in the future. Let's keep it as a property for now, and in the future we can look at adding a full settings object as a parameter to `SoundBox()` once we've got more settings to manage. Example:

```js
let soundboxA = new SoundBox(0.5); // What's that do?
let soundboxB = new SoundBox({
    foo: "bar",
    default_volume: 0.5,
    // ....
}); // Much better, I can see what it does now
```

**Comment by vdeville** [comment]
Ho yeah, that nice with the example of soundboxB

**Comment by sbrl** [comment]
Cool! We'll roll with the in the future once we've got more options then.
